### ISSUE TITLE
Different results between this implementation and original implementation

### ISSUE THREAD

**Issue by Zander1983** [bioturing/logicle-js#5]
When I run the R logicleTransform():

```
lgcl <- logicleTransform( w = 0.0, t= 262144, m = 4.5, a = 0)
res<-lgcl(200000)
res
```

I get the result 4.38249

But when I run this implementation:

```
var res = api.LogicleTransform([200000], 262144, 4.5, 0, 0)
console.log(res);
```

The output of this was 0.9738866831164751. In fact, with this implementation the output is always between 0 and 1 for any input less than 262144. Why is this?

**Comment by JATC1024** [comment]
Hi Zander, thanks for reporting this.
The authors of the [original paper](https://onlinelibrary.wiley.com/doi/full/10.1002/cyto.a.20258) actually released an [update](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4761345) on the transformation. To quote the update:

> "The original specification of the logicle method (1,2) yields a display scale spanning some range of natural or common logarithms. However, for good software practice, it is desirable to scale onto the unit interval [0,1] and use a separate viewing transform to control the layout of the graph on the page or screen. That approach is taken here."

The implementation of this package simply scales the result to [0,1] range. If you want the original result, simply multiply it by `m` (which is 4.5 in your example).

Sorry for the late response, Github did a bad job at notifying me.
Hope this clarifies.

**Comment by JATC1024** [comment]
Close due to inactivity

**Comment by Zander1983** [comment]
Hi @JATC1024 
That makes sense and that's what I suspected, thanks for clarification.
